### Get All Products
GET http://localhost:3000/api/laptops

### Get Product by ID
GET http://localhost:3000/api/laptops/1

### Create New Product
POST http://localhost:3000/api/laptops
Content-Type: application/json

{
    "title": "MSI Prestige 16 AI+ Mercedes-AMG",
    "price": "Rp. 31.999.000"
    "thumbnail": "https://els.id/wp-content/uploads/2025/09/MSI-Prestige-16-AI-MercedesAMG-3.png"
}

### Update Product by ID
PUT http://localhost:3000/api/laptops/11
Content-Type: application/json

{
    "title": "MSI Prestige 16 AI+ Mercedes-AMG Updated",
    "price": "Rp. 32.999.000"
    "thumbnail": "https://els.id/wp-content/uploads/2025/09/MSI-Prestige-16-AI-MercedesAMG-3-updated.png"
}

### Delete Product by ID
DELETE http://localhost:3000/api/laptops/11